{% set version = "0.7.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gdalcubes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gdalcubes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gdalcubes/gdalcubes_{{ version }}.tar.gz
  sha256: e22433df6948efd331c5529bceeba27c71cd0d2d0ebe012bbf09b07b769cfaae

build:
  skip: true  # [win]
  number: 5
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bh                         # [build_platform != target_platform]
    - r-jsonlite                   # [build_platform != target_platform]
    - r-ncdf4                      # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-jsonlite
    - r-ncdf4
    - r-rcpp
    - libnetcdf
    - libgdal
    - proj
    - sqlite
  run:
    - r-base
    - r-jsonlite
    - r-ncdf4
    - r-rcpp
    - libnetcdf
    - libgdal
    - proj
    - sqlite

test:
  requires:
    - r-tinytest
  commands:
    - $R -e "library('gdalcubes')"                          # [not win]
    - $R -e "tinytest::test_package('gdalcubes')"           # [not win]
    - "\"%R%\" -e \"library('gdalcubes')\""                 # [win]
    - "\"%R%\" -e \"tinytest::test_package('gdalcubes')\""  # [win]

about:
  home: https://github.com/appelmar/gdalcubes_R
  license: MIT
  summary: Processing collections of Earth observation images as on-demand multispectral, multitemporal raster data cubes. Users define cubes by spatiotemporal extent, resolution, and spatial reference system and let 'gdalcubes' automatically apply cropping, reprojection, and resampling using the 'Geospatial Data Abstraction
    Library' ('GDAL'). Implemented functions on data cubes include reduction over space and time, applying arithmetic expressions on pixel band values, moving window aggregates over time, filtering by space, time, bands, and predicates on pixel values, exporting data cubes as 'netCDF' or 'GeoTIFF' files, and plotting.  The
    package implements lazy evaluation and multithreading. All computational parts are implemented in C++, linking to the 'GDAL', 'netCDF', 'CURL', and 'SQLite' libraries. See Appel and Pebesma (2019) <doi:10.3390/data4030092> for further details.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
